### ISSUE TITLE
Cannot create a document workflow

### ISSUE THREAD

**Issue by topkool** [danmunn/redmine_dmsf#368]
Redmine 3.0.1

- Open a project and  go to "Settings" -> "Approval workflows" tabs
- Click on "New approval workflow"
- Enter "Name"
- Click on "Create"

Error name => Name cannot be blank

Similar to #367 ?

**Comment by picman** [comment]
Post the log, please.

**Comment by topkool** [comment]
You're right, sorry. Here they are:


Started POST "/dmsf_workflows" for <masked> at 2015-03-26 13:11:51 +0100
Processing by DmsfWorkflowsController#create as HTML
  Parameters: {"utf8"=>"?", "authenticity_token"=>"<masked>", "dmsf_workflow"=>{"name"=>"test"}, "dmsf_workflow_id"=>"0", "project_id"=>"3", "commit"=>"Create"}
  Current user: <masked> (id=8)
WARNING: Can't mass-assign protected attributes for DmsfWorkflow: name

  Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/new.html.erb within layouts/base (2.9ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (2.5ms)
  Rendered plugins/redmine_pretend/app/views/user/_unpretend.html.erb (0.2ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (0.5ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_body_bottom.html.erb (1.2ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_add_form.html.erb (3.8ms)
Completed 200 OK in 76ms (Views: 59.9ms | ActiveRecord: 4.0ms)

**Comment by picman** [comment]
Please re-test it.

**Comment by topkool** [comment]
It works, but there is another issue on the workflow:

- Once the workflow is created, select it
- Select a user and click on "AND"
- Error message "Internal error"

-----------------------

Started POST "/dmsf_workflows/2/edit" for <masked> at 2015-03-26 13:43:11 +0100
Processing by DmsfWorkflowsController#add_step as HTML
  Parameters: {"utf8"=>"?", "authenticity_token"=>"<masked>", "user_search"=>"", "user_ids"=>["8"], "step"=>"0", "commit"=>"AND", "id"=>"2"}
  Current user: <masked> (id=8)
Completed 500 Internal Server Error in 9ms

NoMethodError (undefined method `find_all_by_id' for #<Class:0x00000003b8a0d0>):
  activerecord (4.2.0) lib/active_record/dynamic_matchers.rb:26:in `method_missing'
  plugins/redmine_dmsf/app/controllers/dmsf_workflows_controller.rb:274:in `add_step'
  actionpack (4.2.0) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.0) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.0) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.0) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.0) lib/action_controller/metal.rb:195:in `dispatch'
  actionpack (4.2.0) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.0) lib/action_controller/metal.rb:236:in `block in action'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:42:in `serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:802:in `call'
  rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
  request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
  rack (1.6.0) lib/rack/etag.rb:24:in `call'
  rack (1.6.0) lib/rack/conditionalget.rb:38:in `call'
  rack (1.6.0) lib/rack/head.rb:13:in `call'
  actionpack-xml_parser (1.0.1) lib/action_dispatch/xml_params_parser.rb:16:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.0) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.0) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.0) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.0) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.0) lib/rails/engine.rb:518:in `call'
  railties (4.2.0) lib/rails/application.rb:164:in `call'
  railties (4.2.0) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.0) lib/rails/railtie.rb:194:in `method_missing'
  passenger (4.0.59) lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  passenger (4.0.59) lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  passenger (4.0.59) lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  passenger (4.0.59) lib/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'

**Comment by picman** [comment]
Fixed.

**Comment by topkool** [comment]
The previous is fixed and works fine... but there is a new one :-(

When clicking on "AND" or "OR", an error is dislayed: "An error occured while assigning"

Here is the log:

----------------------


Started POST "/dmsf_workflows/2/edit" for <masked> at 2015-03-26 14:30:18 +0100
Processing by DmsfWorkflowsController#add_step as HTML
  Parameters: {"utf8"=>"?", "authenticity_token"=>"<masked>", "user_search"=>"", "user_ids"=>["8"], "step"=>"0", "commit"=>"AND", "id"=>"2"}
  Current user: <masked> (id=8)
WARNING: Can't mass-assign protected attributes for DmsfWorkflowStep: dmsf_workflow_id, step, user_id, operator

  Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_steps.html.erb (5.9ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/add_step.html.erb within layouts/base (6.4ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (2.3ms)
  Rendered plugins/redmine_pretend/app/views/user/_unpretend.html.erb (0.1ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (0.5ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_body_bottom.html.erb (1.1ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_add_form.html.erb (3.5ms)
Completed 200 OK in 80ms (Views: 61.7ms | ActiveRecord: 3.1ms)

**Comment by picman** [comment]
Please re-test.
Unfortunately I have no Rails 4 environment for testing. So, I'm afraid that we will have to fix all code changes related to Rails 4 one by one.

**Comment by topkool** [comment]
Don't worry, I'm your tester ;-)

Still an issue, but now the browser does not print any error message, but the log does.

I happens when I upload a document.

There are several "DEPRECATION WARNING" and a "WARNING" at the end.

~~~
Started POST "/projects/terminal/dmsf/upload/commit" for <masked> at 2015-03-26 22:13:22 +0100
Processing by DmsfUploadController#commit_files as HTML
  Parameters: {"utf8"=>"?", "authenticity_token"=>"<masked>", "commited_files"=>{"1"=>{"disk_filename"=>"<masked>.pptx", "title"=>"xxxxxx", "name"=>"<masked>.pptx", "description"=>"", "version"=>"3", "custom_version_major"=>"2", "custom_version_minor"=>"0", "comment"=>""}}, "commit"=>"Commit", "id"=>"terminal"}
  Current user: <masked> (id=8)
2015-03-26 22:13:23 <masked>@<masked>: uploaded dmsf://terminal/7/7
DEPRECATION WARNING: The method `dmsf_file_path` cannot be used here as a full URL is required. Use `dmsf_file_url` instead. (called from block in _86a0da12287433851f3319ef6f57053b at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.text.erb:28)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from block in _86a0da12287433851f3319ef6f57053b at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.text.erb:28)
  Rendered plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.text.erb within layouts/mailer (3.2ms)
DEPRECATION WARNING: The method `user_path` cannot be used here as a full URL is required. Use `user_url` instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:21)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:21)
DEPRECATION WARNING: The method `project_path` cannot be used here as a full URL is required. Use `project_url` instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:22)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:22)
DEPRECATION WARNING: The method `dmsf_file_path` cannot be used here as a full URL is required. Use `dmsf_file_url` instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:26)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:26)
DEPRECATION WARNING: The method `dmsf_file_path` cannot be used here as a full URL is required. Use `dmsf_file_url` instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:32)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:32)
  Rendered plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb within layouts/mailer (5.2ms)
DEPRECATION WARNING: The method `dmsf_file_path` cannot be used here as a full URL is required. Use `dmsf_file_url` instead. (called from block in _86a0da12287433851f3319ef6f57053b at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.text.erb:28)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from block in _86a0da12287433851f3319ef6f57053b at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.text.erb:28)
  Rendered plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.text.erb within layouts/mailer (2.5ms)
DEPRECATION WARNING: The method `user_path` cannot be used here as a full URL is required. Use `user_url` instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:21)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:21)
DEPRECATION WARNING: The method `project_path` cannot be used here as a full URL is required. Use `project_url` instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:22)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:22)
DEPRECATION WARNING: The method `dmsf_file_path` cannot be used here as a full URL is required. Use `dmsf_file_url` instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:26)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:26)
DEPRECATION WARNING: The method `dmsf_file_path` cannot be used here as a full URL is required. Use `dmsf_file_url` instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:32)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:32)
  Rendered plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb within layouts/mailer (5.3ms)
DEPRECATION WARNING: The method `dmsf_file_path` cannot be used here as a full URL is required. Use `dmsf_file_url` instead. (called from block in _86a0da12287433851f3319ef6f57053b at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.text.erb:28)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from block in _86a0da12287433851f3319ef6f57053b at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.text.erb:28)
  Rendered plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.text.erb within layouts/mailer (2.4ms)
DEPRECATION WARNING: The method `user_path` cannot be used here as a full URL is required. Use `user_url` instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:21)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:21)
DEPRECATION WARNING: The method `project_path` cannot be used here as a full URL is required. Use `project_url` instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:22)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:22)
DEPRECATION WARNING: The method `dmsf_file_path` cannot be used here as a full URL is required. Use `dmsf_file_url` instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:26)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:26)
DEPRECATION WARNING: The method `dmsf_file_path` cannot be used here as a full URL is required. Use `dmsf_file_url` instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:32)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:32)
  Rendered plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb within layouts/mailer (5.1ms)
DEPRECATION WARNING: The method `dmsf_file_path` cannot be used here as a full URL is required. Use `dmsf_file_url` instead. (called from block in _86a0da12287433851f3319ef6f57053b at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.text.erb:28)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from block in _86a0da12287433851f3319ef6f57053b at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.text.erb:28)
  Rendered plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.text.erb within layouts/mailer (2.5ms)
DEPRECATION WARNING: The method `user_path` cannot be used here as a full URL is required. Use `user_url` instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:21)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:21)
DEPRECATION WARNING: The method `project_path` cannot be used here as a full URL is required. Use `project_url` instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:22)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:22)
DEPRECATION WARNING: The method `dmsf_file_path` cannot be used here as a full URL is required. Use `dmsf_file_url` instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:26)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:26)
DEPRECATION WARNING: The method `dmsf_file_path` cannot be used here as a full URL is required. Use `dmsf_file_url` instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:32)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:32)
  Rendered plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb within layouts/mailer (5.3ms)
DEPRECATION WARNING: The method `dmsf_file_path` cannot be used here as a full URL is required. Use `dmsf_file_url` instead. (called from block in _86a0da12287433851f3319ef6f57053b at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.text.erb:28)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from block in _86a0da12287433851f3319ef6f57053b at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.text.erb:28)
  Rendered plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.text.erb within layouts/mailer (2.4ms)
DEPRECATION WARNING: The method `user_path` cannot be used here as a full URL is required. Use `user_url` instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:21)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:21)
DEPRECATION WARNING: The method `project_path` cannot be used here as a full URL is required. Use `project_url` instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:22)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:22)
DEPRECATION WARNING: The method `dmsf_file_path` cannot be used here as a full URL is required. Use `dmsf_file_url` instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:26)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:26)
DEPRECATION WARNING: The method `dmsf_file_path` cannot be used here as a full URL is required. Use `dmsf_file_url` instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:32)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:32)
  Rendered plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb within layouts/mailer (5.4ms)
DEPRECATION WARNING: The method `dmsf_file_path` cannot be used here as a full URL is required. Use `dmsf_file_url` instead. (called from block in _86a0da12287433851f3319ef6f57053b at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.text.erb:28)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from block in _86a0da12287433851f3319ef6f57053b at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.text.erb:28)
  Rendered plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.text.erb within layouts/mailer (2.5ms)
DEPRECATION WARNING: The method `user_path` cannot be used here as a full URL is required. Use `user_url` instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:21)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:21)
DEPRECATION WARNING: The method `project_path` cannot be used here as a full URL is required. Use `project_url` instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:22)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:22)
DEPRECATION WARNING: The method `dmsf_file_path` cannot be used here as a full URL is required. Use `dmsf_file_url` instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:26)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:26)
DEPRECATION WARNING: The method `dmsf_file_path` cannot be used here as a full URL is required. Use `dmsf_file_url` instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:32)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:32)
  Rendered plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb within layouts/mailer (5.5ms)
DEPRECATION WARNING: The method `dmsf_file_path` cannot be used here as a full URL is required. Use `dmsf_file_url` instead. (called from block in _86a0da12287433851f3319ef6f57053b at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.text.erb:28)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from block in _86a0da12287433851f3319ef6f57053b at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.text.erb:28)
  Rendered plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.text.erb within layouts/mailer (2.4ms)
DEPRECATION WARNING: The method `user_path` cannot be used here as a full URL is required. Use `user_url` instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:21)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:21)
DEPRECATION WARNING: The method `project_path` cannot be used here as a full URL is required. Use `project_url` instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:22)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:22)
DEPRECATION WARNING: The method `dmsf_file_path` cannot be used here as a full URL is required. Use `dmsf_file_url` instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:26)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:26)
DEPRECATION WARNING: The method `dmsf_file_path` cannot be used here as a full URL is required. Use `dmsf_file_url` instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:32)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:32)
  Rendered plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb within layouts/mailer (5.4ms)
DEPRECATION WARNING: The method `dmsf_file_path` cannot be used here as a full URL is required. Use `dmsf_file_url` instead. (called from block in _86a0da12287433851f3319ef6f57053b at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.text.erb:28)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from block in _86a0da12287433851f3319ef6f57053b at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.text.erb:28)
  Rendered plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.text.erb within layouts/mailer (2.4ms)
DEPRECATION WARNING: The method `user_path` cannot be used here as a full URL is required. Use `user_url` instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:21)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:21)
DEPRECATION WARNING: The method `project_path` cannot be used here as a full URL is required. Use `project_url` instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:22)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:22)
DEPRECATION WARNING: The method `dmsf_file_path` cannot be used here as a full URL is required. Use `dmsf_file_url` instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:26)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:26)
DEPRECATION WARNING: The method `dmsf_file_path` cannot be used here as a full URL is required. Use `dmsf_file_url` instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:32)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:32)
  Rendered plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb within layouts/mailer (5.2ms)
DEPRECATION WARNING: The method `dmsf_file_path` cannot be used here as a full URL is required. Use `dmsf_file_url` instead. (called from block in _86a0da12287433851f3319ef6f57053b at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.text.erb:28)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from block in _86a0da12287433851f3319ef6f57053b at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.text.erb:28)
  Rendered plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.text.erb within layouts/mailer (2.4ms)
DEPRECATION WARNING: The method `user_path` cannot be used here as a full URL is required. Use `user_url` instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:21)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:21)
DEPRECATION WARNING: The method `project_path` cannot be used here as a full URL is required. Use `project_url` instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:22)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:22)
DEPRECATION WARNING: The method `dmsf_file_path` cannot be used here as a full URL is required. Use `dmsf_file_url` instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:26)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:26)
DEPRECATION WARNING: The method `dmsf_file_path` cannot be used here as a full URL is required. Use `dmsf_file_url` instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:32)
DEPRECATION WARNING: You are calling a `*_path` helper with the `only_path` option explicitly set to `false`. This option will stop working on path helpers in Rails 5. Use the corresponding `*_url` helper instead. (called from block in _b57b79ea7d5aff3a140357d890f32cbe at /usr/share/redmine-3.0.1/plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb:32)
  Rendered plugins/redmine_dmsf/app/views/dmsf_mailer/files_updated.html.erb within layouts/mailer (5.2ms)
Redirected to http://<masked>/projects/terminal/dmsf
Completed 302 Found in 7640ms (ActiveRecord: 108.9ms)
Started GET "/projects/terminal/dmsf" for 66.249.93.129 at 2015-03-26 22:13:30 +0100
Processing by DmsfController#show as HTML
  Parameters: {"id"=>"terminal"}
  Current user: <masked> (id=8)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.6ms)
WARNING: Can't mass-assign protected attributes for DmsfFolder: project
~~~

**Comment by picman** [comment]
Fixed.

**Comment by topkool** [comment]
1/ There are new warnings after uploading files:

~~~
WARNING: Can't mass-assign protected attributes for DmsfFile: project
WARNING: Can't mass-assign protected attributes for DmsfFileRevision: file
~~~

2/ Warning after assigning a workflow to a document

~~~
WARNING: Can't mass-assign protected attributes for DmsfWorkflowStepAssignment: dmsf_workflow_step_id, user_id, dmsf_file_revision_id
WARNING: Can't mass-assign protected attributes for DmsfWorkflowStepAssignment: dmsf_workflow_step_id, user_id, dmsf_file_revision_id
~~~

3/ Once a workflow is assigned to a document, we can start the workflow by click on the tick located at the right of the DMSF tab.

Once done, I do not see anymore action.
A tip is displayed when the mouse roll over the green tick with the following label as-is: "Approve Reject Delegate to".

What is the next step?

**Comment by picman** [comment]
1+2 fixed
3) It's strange. It should looks like as follows:
* The tick is blue and the tool tip is "Waiting for approval"
* The workflow column text is "Waiting for approval" and the tool tip contains the name of the first approver. If you click on it, the workflow log is displayed.

What values do you see there?

**Comment by topkool** [comment]
The previous fix changed the behavior of 3)
Now, when I click on the blue/green tick (tip="waiting for approval"), a popup is displayed.
Then, I select "Approve", I type a short description, and I click on "Submit"

Error Message = "The note can't be empty"

Log:
~~~
WARNING: Can't mass-assign protected attributes for DmsfWorkflowStepAction: dmsf_workflow_step_assignment_id, action, note
~~~

**Comment by picman** [comment]
Fixed.

**Comment by topkool** [comment]
I think for now every seems to work

**Comment by topkool** [comment]
I think for now every seems to work

**Comment by picman** [comment]
Great!
