### ISSUE TITLE
Failure to Update DMSF from 1.5.9 to 2.0.0 during migrate

### ISSUE THREAD

**Issue by Hofei90** [danmunn/redmine_dmsf#988]
Hello, 
i try to update my Redmine Version from 3.3.4 to 4.0.2 and redmine_dmsf from1.5.9 to 2.0.0.
I get this error message after `bundle exec rake redmine:plugins:migrate RAILS_ENV=production`

> == 20170323131231 DmsfDescriptionLimit: migrating =============================
> -- adapter_name()
>    -> 0.0001s
> -- change_column(:projects, :dmsf_description, :text, {:null=>true, :limit=>6553                                     5})
>    -> 0.0135s
> -- adapter_name()
>    -> 0.0000s
> -- change_column(:dmsf_folders, :description, :text, {:null=>true, :limit=>65535                                     })
>    -> 0.0069s
> == 20170323131231 DmsfDescriptionLimit: migrated (0.0214s) ====================
> 
> == 20170330131901 CreateDmsfFolderPermissions: migrating ======================
> -- adapter_name()
>    -> 0.0001s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:dmsf_folder_permissions, {:options=>"ENGINE=InnoDB", :id=>:inte                                     ger})
>    -> 0.4039s
> -- add_index(:dmsf_folder_permissions, :dmsf_folder_id)
>    -> 0.1250s
> == 20170330131901 CreateDmsfFolderPermissions: migrated (0.5307s) =============
> 
> == 20170421101901 DmsfFileContainerRollback: migrating ========================
> -- add_column(:dmsf_folders, :system, :boolean, {:null=>false, :default=>false})
>    -> 0.2719s
> rake aborted!
> StandardError: An error has occurred, all later migrations canceled:
> 
> Validation failed: Title contains invalid character(s)
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/validations.rb:80:                                     in `raise_validation_error'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/validations.rb:52:                                     in `save!'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:31                                     5:in `block in save!'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:38                                     7:in `block in with_transaction_returning_status'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapter                                     s/abstract/database_statements.rb:259:in `block in transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapter                                     s/abstract/transaction.rb:239:in `block in within_new_transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapter                                     s/abstract/transaction.rb:236:in `within_new_transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapter                                     s/abstract/database_statements.rb:259:in `transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:21                                     2:in `transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:38                                     5:in `with_transaction_returning_status'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:31                                     5:in `save!'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/suppressor.rb:48:i                                     n `save!'
> /opt/redmine/redmine-4.0.2/plugins/redmine_dmsf/db/migrate/20170421101901_dmsf_f                                     ile_container_rollback.rb:52:in `block in up'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.r                                     b:70:in `block (2 levels) in find_each'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.r                                     b:70:in `each'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.r                                     b:70:in `block in find_each'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.r                                     b:136:in `block in find_in_batches'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.r                                     b:238:in `block in in_batches'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.r                                     b:222:in `loop'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.r                                     b:222:in `in_batches'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.r                                     b:135:in `find_in_batches'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.r                                     b:69:in `find_each'
> /opt/redmine/redmine-4.0.2/plugins/redmine_dmsf/db/migrate/20170421101901_dmsf_f                                     ile_container_rollback.rb:29:in `up'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:817:i                                     n `exec_migration'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:798:i                                     n `block (2 levels) in migrate'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:797:i                                     n `block in migrate'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapter                                     s/abstract/connection_pool.rb:416:in `with_connection'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:796:i                                     n `migrate'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:977:i                                     n `migrate'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1292:                                     in `block in execute_migration_in_transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1345:                                     in `ddl_transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1291:                                     in `execute_migration_in_transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1263:                                     in `block in migrate_without_lock'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1262:                                     in `each'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1262:                                     in `migrate_without_lock'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1210:                                     in `block in migrate'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1363:                                     in `with_advisory_lock'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1210:                                     in `migrate'
> /opt/redmine/redmine-4.0.2/lib/redmine/plugin.rb:498:in `up'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1011:                                     in `migrate'
> /opt/redmine/redmine-4.0.2/lib/redmine/plugin.rb:530:in `migrate_plugin'
> /opt/redmine/redmine-4.0.2/lib/redmine/plugin.rb:471:in `migrate'
> /opt/redmine/redmine-4.0.2/lib/redmine/plugin.rb:485:in `block in migrate'
> /opt/redmine/redmine-4.0.2/lib/redmine/plugin.rb:484:in `each'
> /opt/redmine/redmine-4.0.2/lib/redmine/plugin.rb:484:in `migrate'
> /opt/redmine/redmine-4.0.2/lib/tasks/redmine.rake:135:in `block (3 levels) in <t                                     op (required)>'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
> 
> Caused by:
> ActiveRecord::RecordInvalid: Validation failed: Title contains invalid character                                     (s)
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/validations.rb:80:                                     in `raise_validation_error'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/validations.rb:52:                                     in `save!'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:31                                     5:in `block in save!'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:38                                     7:in `block in with_transaction_returning_status'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapter                                     s/abstract/database_statements.rb:259:in `block in transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapter                                     s/abstract/transaction.rb:239:in `block in within_new_transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapter                                     s/abstract/transaction.rb:236:in `within_new_transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapter                                     s/abstract/database_statements.rb:259:in `transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:21                                     2:in `transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:38                                     5:in `with_transaction_returning_status'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:31                                     5:in `save!'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/suppressor.rb:48:i                                     n `save!'
> /opt/redmine/redmine-4.0.2/plugins/redmine_dmsf/db/migrate/20170421101901_dmsf_f                                     ile_container_rollback.rb:52:in `block in up'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.r                                     b:70:in `block (2 levels) in find_each'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.r                                     b:70:in `each'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.r                                     b:70:in `block in find_each'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.r                                     b:136:in `block in find_in_batches'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.r                                     b:238:in `block in in_batches'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.r                                     b:222:in `loop'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.r                                     b:222:in `in_batches'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.r                                     b:135:in `find_in_batches'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.r                                     b:69:in `find_each'
> /opt/redmine/redmine-4.0.2/plugins/redmine_dmsf/db/migrate/20170421101901_dmsf_f                                     ile_container_rollback.rb:29:in `up'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:817:i                                     n `exec_migration'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:798:i                                     n `block (2 levels) in migrate'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:797:i                                     n `block in migrate'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapter                                     s/abstract/connection_pool.rb:416:in `with_connection'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:796:i                                     n `migrate'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:977:i                                     n `migrate'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1292:                                     in `block in execute_migration_in_transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1345:                                     in `ddl_transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1291:                                     in `execute_migration_in_transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1263:                                     in `block in migrate_without_lock'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1262:                                     in `each'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1262:                                     in `migrate_without_lock'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1210:                                     in `block in migrate'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1363:                                     in `with_advisory_lock'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1210:                                     in `migrate'
> /opt/redmine/redmine-4.0.2/lib/redmine/plugin.rb:498:in `up'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1011:                                     in `migrate'
> /opt/redmine/redmine-4.0.2/lib/redmine/plugin.rb:530:in `migrate_plugin'
> /opt/redmine/redmine-4.0.2/lib/redmine/plugin.rb:471:in `migrate'
> /opt/redmine/redmine-4.0.2/lib/redmine/plugin.rb:485:in `block in migrate'
> /opt/redmine/redmine-4.0.2/lib/redmine/plugin.rb:484:in `each'
> /opt/redmine/redmine-4.0.2/lib/redmine/plugin.rb:484:in `migrate'
> /opt/redmine/redmine-4.0.2/lib/tasks/redmine.rake:135:in `block (3 levels) in <t                                     op (required)>'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
> Tasks: TOP => redmine:plugins:migrate
> (See full trace by running task with --trace)

on a second run i get this message ` bundle exec rake redmine:plugins:migrate NAME=redmine_dmsf RAILS_ENV="production" --trace`:

> ** Invoke redmine:plugins:migrate (first_time)
> ** Invoke environment (first_time)
> ** Execute environment
> ** Execute redmine:plugins:migrate
> == 20170421101901 DmsfFileContainerRollback: migrating ========================
> -- add_column(:dmsf_folders, :system, :boolean, {:null=>false, :default=>false})
> rake aborted!
> StandardError: An error has occurred, all later migrations canceled:
> 
> Mysql2::Error: Duplicate column name 'system': ALTER TABLE `dmsf_folders` ADD `system` tinyint(1) DEFAULT FALSE NOT NULL
> /var/lib/gems/2.3.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `_query'
> /var/lib/gems/2.3.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `block in query'
> /var/lib/gems/2.3.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `handle_interrupt'
> /var/lib/gems/2.3.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `query'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:187:in `block (2 levels) in execute'
> /var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
> /var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
> /var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:186:in `block in execute'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block (2 levels) in log'
> /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:578:in `block in log'
> /var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:569:in `log'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:185:in `execute'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/mysql/database_statements.rb:28:in `execute'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:581:in `add_column'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:871:in `block in method_missing'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:840:in `block in say_with_time'
> /usr/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:840:in `say_with_time'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:860:in `method_missing'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration/compatibility.rb:110:in `add_column'
> /opt/redmine/redmine-4.0.2/plugins/redmine_dmsf/db/migrate/20170421101901_dmsf_file_container_rollback.rb:25:in `up'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:817:in `exec_migration'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
> /usr/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:797:in `block in migrate'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:796:in `migrate'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:977:in `migrate'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1345:in `ddl_transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1262:in `each'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1262:in `migrate_without_lock'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1210:in `block in migrate'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1363:in `with_advisory_lock'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1210:in `migrate'
> /opt/redmine/redmine-4.0.2/lib/redmine/plugin.rb:498:in `up'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1011:in `migrate'
> /opt/redmine/redmine-4.0.2/lib/redmine/plugin.rb:530:in `migrate_plugin'
> /opt/redmine/redmine-4.0.2/lib/redmine/plugin.rb:471:in `migrate'
> /opt/redmine/redmine-4.0.2/lib/redmine/plugin.rb:482:in `migrate'
> /opt/redmine/redmine-4.0.2/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
> /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
> /usr/local/bin/rake:22:in `load'
> /usr/local/bin/rake:22:in `<main>'
> 
> Caused by:
> ActiveRecord::StatementInvalid: Mysql2::Error: Duplicate column name 'system': ALTER TABLE `dmsf_folders` ADD `system` tinyint(1) DEFAULT FALSE NOT NULL
> /var/lib/gems/2.3.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `_query'
> /var/lib/gems/2.3.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `block in query'
> /var/lib/gems/2.3.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `handle_interrupt'
> /var/lib/gems/2.3.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `query'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:187:in `block (2 levels) in execute'
> /var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
> /var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
> /var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:186:in `block in execute'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block (2 levels) in log'
> /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:578:in `block in log'
> /var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:569:in `log'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:185:in `execute'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/mysql/database_statements.rb:28:in `execute'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:581:in `add_column'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:871:in `block in method_missing'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:840:in `block in say_with_time'
> /usr/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:840:in `say_with_time'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:860:in `method_missing'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration/compatibility.rb:110:in `add_column'
> /opt/redmine/redmine-4.0.2/plugins/redmine_dmsf/db/migrate/20170421101901_dmsf_file_container_rollback.rb:25:in `up'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:817:in `exec_migration'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
> /usr/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:797:in `block in migrate'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:796:in `migrate'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:977:in `migrate'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1345:in `ddl_transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1262:in `each'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1262:in `migrate_without_lock'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1210:in `block in migrate'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1363:in `with_advisory_lock'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1210:in `migrate'
> /opt/redmine/redmine-4.0.2/lib/redmine/plugin.rb:498:in `up'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1011:in `migrate'
> /opt/redmine/redmine-4.0.2/lib/redmine/plugin.rb:530:in `migrate_plugin'
> /opt/redmine/redmine-4.0.2/lib/redmine/plugin.rb:471:in `migrate'
> /opt/redmine/redmine-4.0.2/lib/redmine/plugin.rb:482:in `migrate'
> /opt/redmine/redmine-4.0.2/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
> /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
> /usr/local/bin/rake:22:in `load'
> /usr/local/bin/rake:22:in `<main>'
> 
> Caused by:
> Mysql2::Error: Duplicate column name 'system'
> /var/lib/gems/2.3.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `_query'
> /var/lib/gems/2.3.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `block in query'
> /var/lib/gems/2.3.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `handle_interrupt'
> /var/lib/gems/2.3.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `query'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:187:in `block (2 levels) in execute'
> /var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
> /var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
> /var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:186:in `block in execute'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block (2 levels) in log'
> /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:578:in `block in log'
> /var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:569:in `log'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:185:in `execute'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/mysql/database_statements.rb:28:in `execute'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:581:in `add_column'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:871:in `block in method_missing'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:840:in `block in say_with_time'
> /usr/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:840:in `say_with_time'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:860:in `method_missing'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration/compatibility.rb:110:in `add_column'
> /opt/redmine/redmine-4.0.2/plugins/redmine_dmsf/db/migrate/20170421101901_dmsf_file_container_rollback.rb:25:in `up'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:817:in `exec_migration'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
> /usr/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:797:in `block in migrate'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:796:in `migrate'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:977:in `migrate'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1345:in `ddl_transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1262:in `each'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1262:in `migrate_without_lock'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1210:in `block in migrate'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1363:in `with_advisory_lock'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1210:in `migrate'
> /opt/redmine/redmine-4.0.2/lib/redmine/plugin.rb:498:in `up'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1011:in `migrate'
> /opt/redmine/redmine-4.0.2/lib/redmine/plugin.rb:530:in `migrate_plugin'
> /opt/redmine/redmine-4.0.2/lib/redmine/plugin.rb:471:in `migrate'
> /opt/redmine/redmine-4.0.2/lib/redmine/plugin.rb:482:in `migrate'
> /opt/redmine/redmine-4.0.2/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
> /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
> /usr/local/bin/rake:22:in `load'
> /usr/local/bin/rake:22:in `<main>'
> Tasks: TOP => redmine:plugins:migrate

Information on my System:

> Environment:
>   Redmine version                4.0.2.stable
>   Ruby version                   2.3.3-p222 (2016-11-21) [arm-linux-gnueabihf]
>   Rails version                  5.2.2
>   Environment                    production
>   Database adapter               Mysql2
>   Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
>   Mailer delivery                smtp
> SCM:
>   Filesystem
> Redmine plugins:
>   no plugin installed
> 
> Package: mariadb-server
> Source: mariadb-10.1
> Version: 10.1.37-0+deb9u1
> 
> Raspbian GNU/Linux 9 (stretch)  4.14.79-v7+

Is this a Bug on DMSF or my Fault? How can fix it?

**Comment by picman** [comment]
It seems that some of your folders have got invalid characters in their names. Try the following command and fix any wrong titles.
```sql
select id, title from dmsf_folders where title REGEXP '[]:<>#%*[[<>%?"\/]';
```

**Comment by Hofei90** [comment]
Hello,
this i get when i execute the command:
`select id, title from dmsf_folders where title REGEXP '[]:<>#%*[[<>%?"\/]';`
> MariaDB [redmine]> select id, title from dmsf_folders where title REGEXP '[]:<>#%*[[<>%?"\/]';
> Empty set (0.00 sec)

**Comment by picman** [comment]
Add 1st error)
I've fixed a bug in DB migration. If you pull the master branch, the migration should be Okay now. Or, you can apply the same change as in https://github.com/danmunn/redmine_dmsf/commit/dda3ae437b8a6cb1a07036d1cf431b84c6e7a57b manually.

Add the other errors)
I'm afraid that you will have to fixed it manually before next migration. Eg.:
```ruby
Mysql2::Error: Duplicate column name 'system': ALTER TABLE dmsf_folders ADD system tinyint(1) DEFAULT FALSE NOT NULL
```
=>
```sql
ALTER TABLE dmsf_folders drop column system;
```

**Comment by Hofei90** [comment]
Ok, i download the master branch and execute the command:
`ALTER TABLE dmsf_folders drop column system;`

now i get this error message after ` bundle exec rake redmine:plugins:migrate NAME=redmine_dmsf RAILS_ENV="production" --trace
` :

> (in /opt/redmine/redmine-4.0.2)
> ** Invoke redmine:plugins:migrate (first_time)
> ** Invoke environment (first_time)
> ** Execute environment
> ** Execute redmine:plugins:migrate
> == 20170421101901 DmsfFileContainerRollback: migrating ========================
> -- add_column(:dmsf_folders, :system, :boolean, {:null=>false, :default=>false})
>    -> 0.1963s
> rake aborted!
> StandardError: An error has occurred, all later migrations canceled:
> 
> Validation failed: Title has already been taken
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/validations.rb:80:in `raise_validation_error'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/validations.rb:52:in `save!'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:315:in `block in save!'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `block in transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
> /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:212:in `transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:315:in `save!'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/suppressor.rb:48:in `save!'
> /opt/redmine/redmine-4.0.2/plugins/redmine_dmsf/db/migrate/20170421101901_dmsf_file_container_rollback.rb:52:in `block in up'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:70:in `block (2 levels) in find_each'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:70:in `each'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:70:in `block in find_each'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:238:in `block in in_batches'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:222:in `loop'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:222:in `in_batches'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:135:in `find_in_batches'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:69:in `find_each'
> /opt/redmine/redmine-4.0.2/plugins/redmine_dmsf/db/migrate/20170421101901_dmsf_file_container_rollback.rb:29:in `up'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:817:in `exec_migration'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
> /usr/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:797:in `block in migrate'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:796:in `migrate'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:977:in `migrate'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1345:in `ddl_transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1262:in `each'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1262:in `migrate_without_lock'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1210:in `block in migrate'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1363:in `with_advisory_lock'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1210:in `migrate'
> /opt/redmine/redmine-4.0.2/lib/redmine/plugin.rb:498:in `up'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1011:in `migrate'
> /opt/redmine/redmine-4.0.2/lib/redmine/plugin.rb:530:in `migrate_plugin'
> /opt/redmine/redmine-4.0.2/lib/redmine/plugin.rb:471:in `migrate'
> /opt/redmine/redmine-4.0.2/lib/redmine/plugin.rb:482:in `migrate'
> /opt/redmine/redmine-4.0.2/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
> /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
> /usr/local/bin/rake:22:in `load'
> /usr/local/bin/rake:22:in `<main>'
> 
> Caused by:
> ActiveRecord::RecordInvalid: Validation failed: Title has already been taken
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/validations.rb:80:in `raise_validation_error'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/validations.rb:52:in `save!'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:315:in `block in save!'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `block in transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
> /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:212:in `transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:315:in `save!'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/suppressor.rb:48:in `save!'
> /opt/redmine/redmine-4.0.2/plugins/redmine_dmsf/db/migrate/20170421101901_dmsf_file_container_rollback.rb:52:in `block in up'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:70:in `block (2 levels) in find_each'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:70:in `each'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:70:in `block in find_each'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:238:in `block in in_batches'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:222:in `loop'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:222:in `in_batches'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:135:in `find_in_batches'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:69:in `find_each'
> /opt/redmine/redmine-4.0.2/plugins/redmine_dmsf/db/migrate/20170421101901_dmsf_file_container_rollback.rb:29:in `up'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:817:in `exec_migration'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
> /usr/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:797:in `block in migrate'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:796:in `migrate'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:977:in `migrate'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1345:in `ddl_transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1262:in `each'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1262:in `migrate_without_lock'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1210:in `block in migrate'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1363:in `with_advisory_lock'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1210:in `migrate'
> /opt/redmine/redmine-4.0.2/lib/redmine/plugin.rb:498:in `up'
> /var/lib/gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/migration.rb:1011:in `migrate'
> /opt/redmine/redmine-4.0.2/lib/redmine/plugin.rb:530:in `migrate_plugin'
> /opt/redmine/redmine-4.0.2/lib/redmine/plugin.rb:471:in `migrate'
> /opt/redmine/redmine-4.0.2/lib/redmine/plugin.rb:482:in `migrate'
> /opt/redmine/redmine-4.0.2/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
> /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
> /var/lib/gems/2.3.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
> /usr/local/bin/rake:22:in `load'
> /usr/local/bin/rake:22:in `<main>'
> Tasks: TOP => redmine:plugins:migrate

Unfortunately, I can't help myself in ruby at all. I haven't really figured out the system yet.

**Comment by picman** [comment]
One more improvement. Please `git pull` and try it again.

**Comment by Hofei90** [comment]
Thank you - now it works.

However, I still have a problem. 
But this will probably be better dealt with in a new issue?!
But this has more to do with the fact that I changed the storage path.

Old version:
`/opt/redmine/files/dmsf`
New Version:
`/opt/redmine/redmine-4.0.2/files/dmsf`
Now I get displayed on the web interface when I select a file in DMS: 
404 - The requested page does not exist or has been removed. Also, when migrating, the corresponding messages appear.

In the administration interface I have entered the new absolute path, how do I manage to find the files again?
![dmsf_pfad](https://user-images.githubusercontent.com/29521028/55142547-3117a980-513d-11e9-9758-563993677382.JPG)

**Comment by picman** [comment]
The migration should have reorganized files. They used to be organized by the project identifiers dmsf/p_my_project/, but now they are organized by creation date dmsf/2019/03/. If the migration failed to move files to the new location from whatever reason, you must move them manually.

Please see #799 and #767 for a solution.

**Comment by Hofei90** [comment]
Okay, I'll look at the two issues shown.
If I don't get it right, I'll get back to you ;)

Many thanks for your quick help and at this point also a big thank you and a big praise for the really practical and well working DMSF plugin which is provided for free as Open Source Software - thank you!
